# ekf_node_odometry_imu_vo:
#     ros__parameters:
#         frequency: 30.0              # How frequently we publish (even if filter has not updated)
#         sensor_timeout: 0.1          # If no sensor data in this time, we do a prediction (without correction)
#         two_d_mode: true             # If enabled, 3D dimensions (z, roll, pitch, and their derivatives) are forced to 0
#         transform_timeout: 0.0       # How long to wait for required transforms to be available
#         print_diagnostics: true      # Whether to publish diagnostics

#         map_frame: map                    # The name of your REP-105 map frame (not needed if world_frame == odom_frame)
#         odom_frame: odom             # The name of your REP-105 odom frame
#         base_link_frame: base_link   # The name of your REP-105 base_link frame. Will be the child_frame_id in the output.
#         world_frame: odom            # The world frame that will be the frame_id in the output.
#         publish_tf: false
#         #initial_state: [-465.90, -834.2617, 0.0, 0.0, 0.0, -1.584, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

#         odom0: odom_wheel                       # Topic type + number (odomN, poseN, twistN, imuN) and name
#         odom0_config: [false, false, false,   # x, y, z
#                         false, false, false,   # roll, pitch, yaw
#                         true, true,  false,   # x velocity, y velocity, z velocity
#                         false, false, true,    # roll velocity, pitch velocity, yaw velocity
#                         false, false, false]   # x acceleration, y acceleration, z acceleration

# #---------> Fill these out
#         odom1: odom_morb
#         odom1_differential: false
#         odom1_config: [true, true, false,
#                         false, false, true,
#                         false, false, false,
#                         false, false, false,
#                         false, false, false]

#         imu0: imu
#         imu0_config: [false, false, false,
#                         false, false, false,
#                         false, false, false,
#                         false,  false, true,
#                         true, false, false]
#         imu0_remove_gravitational_acceleration: true
#         # # The Q matrix
#         # initial_estimate_covariance: [1e-9, 1e-9, 1e-9,
#         #                               1e-9, 1e-9, 1e-9,
#         #                               1e-9, 1e-9, 1e-9,
#         #                               1e-9, 1e-9, 1e-9,
#         #                               1e-9, 1e-9, 1e-9]
#         # process_noise_covariance: [1e-9, 1e-9, 1e-9,
#         #                            1e-9, 1e-9, 1e-9, 
#         #                            1e-9, 1e-9, 1e-9,
#         #                            1e-9, 1e-9, 1e-9,
#         #                            1e-9, 1e-9, 1e-9]
#         # dynamic_process_noise_covariance: true  # Whether we scale Q based on the robot's velocity

ekf_node_tier1:
    ros__parameters:
        frequency: 20.0              # How frequently we publish (even if filter has not updated)
        sensor_timeout: 0.04         # If no sensor data in this time, we do a prediction (without correction)
        two_d_mode: true             # If enabled, 3D dimensions (z, roll, pitch, and their derivatives) are forced to 0
        transform_timeout: 0.0       # How long to wait for required transforms to be available
        print_diagnostics: true      # Whether to publish diagnostics

        smooth_lagged_data: true
        history_length: 1.0
        predict_to_current_time: true
        # initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        # initial_estimate_covariance: [1e-9, 1e-9, 1e-9,
        #                               1e-9, 1e-9, 1e-9,
        #                               1e-9, 1e-9, 1e-9,
        #                               1e-9, 1e-9, 1e-9,
        #                               1e-9, 1e-9, 1e-9]
        # process_noise_covariance: [1e-9, 1e-9, 1e-9,
        #                            1e-9, 1e-9, 1e-9,
        #                            1e-9, 1e-9, 1e-9,
        #                            1e-9, 1e-9, 1e-9,
        #                            1e-9, 1e-9, 1e-9]
        # dynamic_process_noise_covariance: true


        map_frame: map                    # The name of your REP-105 map frame (not needed if world_frame == odom_frame)
        odom_frame: odom             # The name of your REP-105 odom frame
        base_link_frame: base_link   # The name of your REP-105 base_link frame. Will be the child_frame_id in the output.
        world_frame: odom            # The world frame that will be the frame_id in the output.

        # Continuous input sources
        odom0: odom_wheel                       # Topic type + number (odomN, poseN, twistN, imuN) and name
        odom0_config: [false, false, false,   # x, y, z
                        false, false, false,   # roll, pitch, yaw
                        true,  true,  false,   # x velocity, y velocity, z velocity
                        false, false, true,    # roll velocity, pitch velocity, yaw velocity
                        false, false, false]   # x acceleration, y acceleration, z acceleration

        # odom1: odom_morb
        # odom1_differential: false
        # odom1_config: [false, false, false,
        #                 false, false, false,
        #                 true,  true, false,   # vx only
        #                 false, false, true,    # wz
        #                 false, false, false]

        imu0: imu
        imu0_config: [false, false, false,
                        false, false, false,
                        false, false, false,
                        false, false, true,
                        true, false, false]
        imu0_remove_gravitational_acceleration: true

ekf_node_tier2:
    ros__parameters:
        frequency: 20.0
        sensor_timeout: 0.04
        two_d_mode: true
        transform_timeout: 0.0
        print_diagnostics: true

        smooth_lagged_data: true
        history_length: 1.0
        predict_to_current_time: true
        # initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        
        # You can tweak these further to "trust but not completely" the global pose
        # initial_estimate_covariance: [1e-9, 1e-9, 1e-9,
        #                               1e-9, 1e-9, 1e-9,
        #                               1e-9, 1e-9, 1e-9,
        #                               1e-9, 1e-9, 1e-9,
        #                               1e-9, 1e-9, 1e-9]
        # process_noise_covariance: [1e-9, 1e-9, 1e-9,
        #                            1e-9, 1e-9, 1e-9,
        #                            1e-9, 1e-9, 1e-9,
        #                            1e-9, 1e-9, 1e-9,
        #                            1e-9, 1e-9, 1e-9]
        # dynamic_process_noise_covariance: true

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: map                 # <-- second tier is in the map frame

        # Continuous input sources (same as tier1)
        odom0: odom_wheel                       # Topic type + number (odomN, poseN, twistN, imuN) and name
        odom0_config: [false, false, false,   # x, y, z
                        false, false, false,   # roll, pitch, yaw
                        true,  true,  false,   # x velocity, y velocity, z velocity
                        false, false, true,    # roll velocity, pitch velocity, yaw velocity
                        false, false, false]   # x acceleration, y acceleration, z acceleration

        # odom1: odom_morb
        # odom1_differential: false
        # odom1_config: [false, false, false,
        #             false, false, false,
        #             true,  true, false,   # vx only
        #             false, false, true,    # wz
        #             false, false, false]

        imu0: imu
        imu0_config: [false, false, false,
                        false, false, false,
                        false, false, false,
                        false, false, true,
                        true, false, false]
        imu0_remove_gravitational_acceleration: true

        # Global pose source(s)
        pose0: amcl_pose
        pose0_config: [true, true, false,   # x, y, z
                        false, false, true,    # roll, pitch, yaw
                        false, false, false,   # x vel, y vel, z vel
                        false, false, false,   # roll vel, pitch vel, yaw vel
                        false, false, false]   # x acc, y acc, z acc
